run:
  deadline: 5m
  allow-parallel-runners: true

linters:
  enable-all: true
  disable:
    - interfacer
    - golint
    - scopelint
    - maligned
    - varnamelen
    - exhaustivestruct
    - ifshort
    - lll
    - goerr113
    - errchkjson
    - goconst
    - nonamedreturns
    - gomoddirectives
    - exhaustruct

issues:
  exclude-rules:
    - path: _unit_test\.go
      linters:
        - testpackage
    - path: _test\.go
      linters:
        - funlen
        - wrapcheck
        - wsl
        - forcetypeassert

linters-settings:
  gci:
    local-prefixes: github.com/saiko-tech/bsp-tracer
  gomnd:
    ignored-numbers:
      - '0666'
      - '0755'
      - '0.5'
      - '2'
      - '10'
